### ISSUE TITLE
package release on CRAN/bioconductor

### ISSUE THREAD

**Issue by nick-youngblut** [reptalex/phylofactor#11]
As far as I can tell, `phylofactor` is not currently available on CRAN or bioconductor. This lack of availability of `phylofactor` from these standard package repositories makes it difficult to install `phylofactor` (eg., via CRAN or anaconda) and integrate it into pipelines and reproducible research environments. Do you have plans to release `phylofactor` on CRAN or bioconductor anytime soon?

**Comment by reptalex** [comment]
I do. Unfortunately, the method has been in further development beyond compositional data analysis, and consequently, to avoid the challenges of back-compatibility, I’ve been keeping it in flux on GitHub.

The readme on the github page shows how to install the bioconductor dependencies & the R package - does that not work for you?

Thanks for the email. Hope we can get this working for ya!
-Alex

**Comment by nick-youngblut** [comment]
Thanks for the quick response! The main challenge with `devtools::install_github` is that there's no way (that I know of) to create a conda package from the GitHub repository. `conda skeleton cran` works quite well for CRAN packages (I'm not sure about bioconductor). My lab uses conda for creating/managing reproducible data analysis environments (we can't use Docker for technical reasons), so if we can't find/create a conda package for some particular software, that particular software becomes a real challenge to install/maintain in a sustainable and reproducible manner.

**Comment by reptalex** [comment]
Hmmm... that sounds like a bit of a snag! Unfortunately, I’m pretty inexperienced at coding (was mainly a mathematician before learning R for this package), so I doubt I could figure out how to make a Vonda package from this any better than you can.

However, I’ll try to expedite the process of submitting this package CRAN.

Thanks again for your comment - if there’s anything else I can do to help out, let me know!

**Comment by nick-youngblut** [comment]
I asked `conda` developers about using `conda skeleton cran` directly on GitHub repos, and it's possible, but the repo has to include at least 1 release tag (see [this issue](https://github.com/conda/conda/issues/6674#issuecomment-355814072)). Could make a release tag for `phylofactor`? It would be much appreciated!

**Comment by reptalex** [comment]
I can definitely try! I read the thread and couldn’t find the link illustrating a proper DESCRIPTION format for this (just that it had to be in the right format). If you happen to find one, please send it my way! In the meantime, I’ll google away and see if I can fix this.

**Comment by nick-youngblut** [comment]
Great! As far as I can tell, the DESCRIPTION for phylofactor looks good. Maybe just the release tag is all that’s needed???

**Comment by reptalex** [comment]
Is that a line saying:

release: 0.0.1

or something like that?

**Comment by nick-youngblut** [comment]
I actually don't have a lot of experience with release tags myself, but I think you can just follow the [GitHub documentation](https://help.github.com/articles/creating-releases/)

**Comment by reptalex** [comment]
Thanks for that link - I just published a release. Let me know if this
hasn't resolved the issue.

**Comment by reptalex** [comment]
No plans to make an official CRAN release in the near future - the S3 and back-compatibility requirements for CRAN releases make CRAN submission an unprofitable effort given this method is still in active development (e.g. the summary(), plot() and print() functions are evolving as we better understand what to summarize, plot and print; the underlying architecture of phylofactorization may change considerably with some updates still in active development, and more).

The current installation steps should work to install the package on Conda (this is a bug I've recently fixed), and for reproducibility you'll just have to note the version of the release on Github.
