### ISSUE TITLE
cast taxonomies to character or warn?

### ISSUE THREAD

**Issue by tanaes** [reptalex/phylofactor#13]
pf.taxa requires the taxonomy column of taxonomies to be a character vector, but R loves to represent things as factors. 

If you try and run pf.taxa with a factor, you get this error:

```
Error in base::endsWith(output, ";"): non-character object(s)
Traceback:

1. pf.taxa(pf_ExPlate_var, taxonomy, factor = i)
2. uniqueTaxa(t1, t2) %>% unique
3. eval(lhs, parent, parent)
4. eval(lhs, parent, parent)
5. uniqueTaxa(t1, t2)
6. base::endsWith(output, ";")
```

It would be nice to have a more explicit test to warn (or coerce).

**Comment by reptalex** [comment]
Hi Jon!

I can't reproduce this error by making a taxonomy (the first, second, or both columns) into a factor, making me think something else is going on. The error occurs in the function `uniqueTaxa` after finding out which taxonomic groups are unique to a given factor. 

Is it possible you have some null entries or entries that are not semicolon-delimited in your taxonomy?

Try to run the following code (pf.taxa) with your phylofactor object, `pf`, `taxonomy` and `factor` that's causing trouble:

`g1 <- pf$tree$tip.label[pf$groups[[factor]][[1]]]`
`g2 <- pf$tree$tip.label[pf$groups[[factor]][[2]]]`
                            
`t1 <- taxonomy[match(g1,taxonomy[,1]),2]`
`t2 <- taxonomy[match(g2,taxonomy[,1]),2]`

If you can send me the `t1` and `t2`, I can get to the bottom of it.  Alternatively, if you'd like to debug further, the next lines of `pf.taxa` are `uniqueTaxa(t1,t2)` and `uniqueTaxa(t2,t1)` - the error is occurring in one of those (maybe `t1` or `t2` are NULL - if your taxonomy doesn't match your tree tip-labels, that could be the issue).

**Comment by tanaes** [comment]
Yup, there are 'Unassigned' entries. I'll see if I can reproduce with a
small ad hoc example.

**Comment by reptalex** [comment]
Gotcha - I was able to reproduce that. If the taxonomy is a factor and one of your groups was uniquely defined as only "Unassigned" without any semicolons, the error occurs.

I've just pushed a change that should fix it without introducing bugs elsewhere.

Thanks for pointing this out!

**Comment by tanaes** [comment]
Amazing! I was trying to reconstruct and failed. Glad you were able to track it down. :) I'll keep things coming as I discover!
