### ISSUE TITLE
FTmicrobiome$PF$choice not existing

### ISSUE THREAD

**Issue by gvdr** [reptalex/phylofactor#14]
When I try to follow the tutorial
```
pf <- FTmicrobiome$PF
```
produces the error `Error in if (PF$choice == "var") { : argument is of length zero`. I think it is because `PF` does not have `choice`.

**Comment by reptalex** [comment]
Gotcha - thanks for catching that. The old phylofactor objects didn't record the choices ('var','F','max.var') which are used in summary functions. 

I've uploaded new phylofactor objects which should work - reinstalling the package should make the tutorial flow smoothly.
