### ISSUE TITLE
Extract OTUs for each factor

### ISSUE THREAD

**Issue by SilasK** [reptalex/phylofactor#16]
Hey @reptalex, 

I continue to try out phylofactor for 16S data. I build a tree by aligning the sequences for each OTU. 

I run phlofactor on the raw counts, which gives me a number of interesting factors.
I would now find out wihch OTUs belong to which factor (smaller group, Group1?).

How can I extract which subtree are selected by pylofactor and wihc OTUs are on that subtree?

**Comment by SilasK** [comment]
Ok found it
pf.groupsTospecies

**Comment by reptalex** [comment]
Two other tools at your disposal are the pf.taxa(pf,taxonomy,factor) and summary(pf,taxonomy,factor) functions.

Make your taxonomy a data frame with the first column being OTUs found in the tree and the second column being semicolon delimited taxonomy (e.g. "k_Bacteria; p_Firmicutes; ...") and pf.taxa will output the shortest unique taxonomic prefixes summarizing the species in the group. summary.phylofactor will do you one extra (may take a bit longer) by recomputing your objective function for each of those taxonomic prefixes, allowing you to see which groups contributed most to the signal and thereby let you choose a decent taxonomic name for the factor.

**Comment by SilasK** [comment]
Great, thank you!
I'm now using now a formula ~Treatment + Source. Is there a way to see
which factor is significantly different for Treatment or for Source? Or
should I run summary.phylofactor and then do a secondary analysis?




>

**Comment by reptalex** [comment]
I'm assuming you mean frmla = Data~Treatment+Source, yeah?

Check out pf$models - you can apply functions over those, such as:

lapply(pf$models,summary) %>% lapply(getElement,'coefficients') %>% ...

here "..." can be a final sapply to extract t-values or z-values (whichever it is).

You can also look into the package "relaimpo" and sapply some relative importance function on the glms. This is what we did with the Central Park soil data to find that pH is the dominant driver of variation across most factors.

If you want to partition based on just one, e.g. find significant treatment factors when controlling for source, then you can make a customized objective function. There's a demo of this in ? PhyloFactor, and it can be done easily if you copy-paste the function GAM and preserve the PF.output if/else statement. Notice that the factor maximizing the output$objective will be chosen, so be careful about sign (e.g. if a strong, negative impact is important, then be sure to take the absolute value of the z-value for Treatment as your output$objective). outpt$stop.statistic (double check the syntax) can be input into a stop.fcn if you want to define as stopping criteron or utput P-values associated with your output$objective to use the default KS-test of uniformity.

**Comment by reptalex** [comment]
When controlling for "source", beware of the potential for extremely different communities to have extremely different effects due to compositional funkiness. For example, maybe in Source 1, there exists a paraphyletic remainder with no species sensitive to treatment, whereas in Source 2 there are large, new lineages which are sensitive, thereby impacting your ability to find a common treatment signal across Sources. This is what we encountered when comparing soil & sludge treated with copper in the Microbiome stress project; for us, a more stable output was to do separate phylofactorizations and map them to the same, universal tree.

https://www.frontiersin.org/articles/10.3389/fmicb.2018.03272/full
