### ISSUE TITLE
Problem with example code for pf.heatmap() using predict()

### ISSUE THREAD

**Issue by mikemc** [reptalex/phylofactor#17]
Thanks for this very useful package. In experimenting I noticed that the documentation for `pf.heatmap()` gives the example
```r
pred <- predict(PF,factors=1:3)
predicted <- pf.heatmap(PF,Data=pred,factors=1:3,width=3)
```
But running this example code shows all factors on the heatmap. The problem seems to be that `predict()` wants `factor = max_factor` (as described in it's documentation), rather than `factors = list_of_factors`. This works as expected:
```r
pred <- predict(PF,factor=3)
predicted <- pf.heatmap(PF,Data=pred,factors=1:3,width=3)
```

**Comment by reptalex** [comment]
Thanks for finding this! Let me make some edits as needed, hopefully resolving this over the next week or so.

Some of the `predict` functionality is still in development, so if you find some predictions you'd like to do but can't, just let me know!

**Comment by reptalex** [comment]
Fixed - thanks for pointing this out!
