### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by jysi-lab** [reptalex/phylofactor#18]
Thanks for this great tool. I was trying to install the package but failed both for Mac and window. I first installed Biostrings (v.2.50.2), ggtree (v.1.14.6), BioManager(v.1.30.4), devtools(v.2.0.1) and was ready to install phylofactor. But it only shows a popup saying 'builing R package from source requires installation of additional build tools.' And when i click yes, there's an error message "Error: Could not find tools necessary to compile a package."
What else do i need to intall?

**Comment by reptalex** [comment]
Hi there!

It looks like you're experiencing a problem similar to the one encountered in the link below:

[https://github.com/rstudio/tensorflow/issues/133]

Let me know if that doesn't help! If this pops up more than once, I'll change the instructions on the readme & tutorial to streamline installation. Thanks for pointing this out!
