### ISSUE TITLE
Error when running phylofactor with 40+ factors

### ISSUE THREAD

**Issue by earmingol** [reptalex/phylofactor#19]
When I was running an analysis with over 40 factors this error showed up, so the analysis was not completed. When I run it with less than 40 factors I had no errors.

My dataset has ~7k samples and 6.5k OTUs

Error in unserialize(node$con) : error reading from connection   
Calls: PhyloFactor ... FUN -> recvData -> recvData.SOCKnode -> unserialize

The specs of where I run the analysis are:
16 cores
8 GB of ram

**Comment by reptalex** [comment]
You're probably trying to use more RAM than you have on your machine. 

In its current implementation, phylofactor requires sending a copy of your dataset to each core. If you make 16 cores (or 15, as recommended practice), then you need 16 copies of your dataset, and that could easily use all 8GB of RAM.

**Comment by reptalex** [comment]
Let me know if memory isn't the problem, though. There are a lot of other forums that have touched on this question and both implicate RAM:

[here](https://www.google.com/search?q=Error+in+unserialize(node$con)+%3A+error+reading+from+connection&ie=&oe=)

[here](https://github.com/stan-dev/rstan/issues/243)

and others

**Comment by earmingol** [comment]
Thanks @reptalex for your answer. It definitely looks like a RAM problem. I tried running it again with 16 cores and 126 GBs and this time it crashed with 99 factors. I am wondering if it is any way to store a sort of checkpoints and not lose the factors calculated until that point?

**Comment by reptalex** [comment]
Hi @earmingol - glad to hear we traced it down.

What caused it to crash? I've been thinkin about adding in a tryCatch to stop some of the most common causes of crashes, however I'll need to hear a bit more about the common causes of crashes to make that update. Was it RAM, or something else?

**Comment by earmingol** [comment]
This time I got the same error than before, but this time the analysis computed more factors, so it looks like a RAM problem I think.

**Comment by reptalex** [comment]
Huh - if I had to take a guess, I'd guess that the RAM consumption is coming from the glm objects that accumulate. 

Try adding the following inputs to PhyloFactor:

`PhyloFactor(...,y=FALSE, model=FALSE,small.output=TRUE,...)`

The idea here is that the first two inputs will help you [trim the fat off the glm](http://www.win-vector.com/blog/2014/05/trimming-the-fat-from-glm-models-in-r/) and the last input removes the pf$models[[i]]$data from each model.

Let me know if that doesn't work, and we can try to rig something for ya.

**Comment by reptalex** [comment]
P.S. Some RAM accumulation is inevitable as the phylofactor object grows. To troubleshoot, I'd make a phylofactor object with fewer factors, and then `sapply(pf,object.size)` to find out which parts of the phylofactor object take up the most memory.

If it's the `pf$models`, as I guess above, one option is to customize your output by customizing the `choice.fcn` - see the example in `? PhyloFactor` for how to customized your objective function, and when `PF.output=TRUE` have the function return an object of smaller size (e.g. the coefficients from regression). If you go this route, you'll have to do some tinkering to get the pf.heatmap function to work, and you'll have to write your own function to predict things depending on the output you provide.

**Comment by earmingol** [comment]
> `PhyloFactor(...,y=FALSE, model=FALSE,small.output=TRUE,...)`

Putting the first two inputs generates the following error:
`Error: $ operator is invalid for atomic vectors`

And considering only the last one seems to work ( I tried with few factors), but, as you mentioned, there is a problem when you try to generate all the post-analyses (e.g. pf.heatmap and pf.tree) because of some parts of the pf object are missing.

For example, for the pf.heatmap I got this:
```
Error in PF$transform.fcn(PF$Data): non-numeric argument to mathematical function
Traceback:

1. pf.heatmap(pf_PhyloFactor, factors = 1:factors, column.order = order(MetaData[, 
 .     phenotype]))
2. as.data.frame(PF$transform.fcn(PF$Data))
```

and for pf.tree:
```
Error in UseMethod("Ntip"): no applicable method for 'Ntip' applied to an object of class "NULL"
Traceback:

1. pf.tree(pf_PhyloFactor, size = 0.25)
2. ape::Ntip(tree)
```

**Comment by reptalex** [comment]
Got it - I made an edit to the package which should allow `y=FALSE` and `model=FALSE` inputs for glm (the previous version didn't allow `y=FALSE` because the function pglm had another input `y`).

Reinstall the package (you should only have to do `devtools::install_github('reptalex/phylofactor')`) and those arguments should work now and reduce your RAM consumption somewhat. However, note that another route is to lower your `ncores` argument - it'll take longer, but you'll have more RAM. Document your RAM accumulation over time and some accounting can help you estimate how much memory you need for how many factors and, consequently, how many cores you can run while still leaving enough RAM to make the phylofactor object.

Hope this helps - happy factorin'!

**Comment by earmingol** [comment]
Thanks @reptalex ! this was very helpful 👍
