### ISSUE TITLE
Unequal Number of Samples

### ISSUE THREAD

**Issue by jrede** [reptalex/phylofactor#20]
Hi @reptalex ,

I've really enjoyed using this package, but I was wondering how Phylofactor deals with uneven sampling. For example, if I had 50 samples from one community and 25 from another, should I attempt to normalize the number of samples before comparing them?  Thanks!

**Comment by reptalex** [comment]
Hi there @jrede!

Glad to hear you like the package! 

The functions PhyloFactor and gpf are wrappers computing desired objectives from generalized linear models. Under the default objectives ('F' or 'var'), PyloFactor's optional input arguments are piped straight into `glm(…)` - that's the easiest you can make changes such as weights, offsets, subsets, etc. Whatever your goodness of fit you want from a glm, phylofactor will iteratively find the edges which maximize that. 

That's how the package works - the default is to use the default weights. The question of what you _ought_ to do with uneven sample size for a single generalized linear model is a question for standard statistics and generalized linear models, discussed in great detail in various textbooks & I'm sure on stack exchange. Consider finding a statistician near you to help you answer this for the purposes of your experiment. I own a statistical consulting company that runs analyses like this (e.g. beyond the basics of how the package works) and my company's rate is $300/hr for stats consulting if you're interested (or package deals of minimum $4k/month for long-term stats goals)!

Best,
Alex
