### ISSUE TITLE
How to deal with nested data?

### ISSUE THREAD

**Issue by yanxianl** [reptalex/phylofactor#23]
Hi Alex,

Phylofactor is a great tool to incorporate phylogeny into the analysis of amplicon data in a CoDA manner.

I want to apply Phylofactor to identify balances that distinguish the gut microbiota of wild tilapia to farmed tilapia. The farmed fish were taken from different ponds and the wild fish were taken from different locations in a lake. Thus, the experiment is a nested design. Is there a way to deal with this kind of dependency structure in the metadata when running the Phylofactor for variables of interests?

Regards,
Yanxian

**Comment by reptalex** [comment]
Hi Yanxian -

Check out [the ecological monograph](https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/ecm.1353), which shows how the general algorithm is structured. Both `PhyloFactor` and `gpf` allow an extremely flexible interface with the data, allowing you to control for fixed/random effects (e.g. 'site') and phylofactor based on other covariates (e.g. 'wild/farmed'). The help files (`? PhyloFactor` and `? gpf`) document how you can make such customized objective functions. If you have questions about which ones to use, try to consult a statistician near you. 

For statistics beyond how the algorithsm work, including the exact construction of customized objectives and the likes, I offer consulting services starting at $200/hr, but you may be able to find a better deal near you.

Hope this helps!
-Alex

**Comment by yanxianl** [comment]
Hi Alex,

I actually did read the _esa_ paper and look at the help files for the `PhyloFactor` and `gpf` but did not find explicit explanations on how to make customized objective functions to deal with random effects. I'll dig into the details and see how to do that.

Good to know that you also provide statistical consultancy.

Thanks for your suggestion.

Best,
Yanxian

**Comment by reptalex** [comment]
The main detail to keep in mind is that phylofactorization maximizes an objective at each iteration. Define an objective using a fixed/random effects model with the function of your choice (the custom objectives show how to interface with the balances or the modified data table containing the `phylo` factor), and you're set!
