### ISSUE TITLE
glm is not working

### ISSUE THREAD

**Issue by nataliagaeta29** [reptalex/phylofactor#24]
Hello
I was following the tutorial, and the R keeps saying that "no glm was found".
I attached print screens from either "my tutorial results" and the "web site results", below, regarding to the construction of the PF for factor 1. The "glm" does not appear in my results and, then, I cannot run any function that requires the glm.
Could you please help me with this issue?

Thanks!

**My results**
![running_tutorial result](https://user-images.githubusercontent.com/54448811/63804957-54aa7000-c8e6-11e9-8bfa-1884070b7531.png)

**Web site results**
![web_site_tutorial](https://user-images.githubusercontent.com/54448811/63804958-54aa7000-c8e6-11e9-81f3-1c2c76e03199.png)

**Comment by reptalex** [comment]
Hi there!

It's unclear where you're hitting the error, but since making the tutorial I've changed the name of "glms" to "models" (as "models" can now also contain gams and a whole suite of other things with a common interface with `predict`). So, `PF$models[[1]]` will get you your glms!

**Comment by reptalex** [comment]
P.S. I've double checked, and I can't seem to find any mention of the old `pf$glms` in the new tutorial (you might be using the tutorial from the PeerJ paper?). 

The updated tutorial is available on the ["Resources" tab of my personal webpage - here](https://www.alexwashburne.com/blog).

**Comment by nataliagaeta29** [comment]
Hi!

Yeah, I was following the PeerJ paper.
But since I changed glm to models, it worked!

Thank you so much for your attention and help.

Regards

Natalia

Get Outlook for Android<https://aka.ms/ghei36>
