### ISSUE TITLE
cmultrepl and Zeros

### ISSUE THREAD

**Issue by biggs-biggsby** [reptalex/phylofactor#26]
Hi @reptalex !

I started using cmultrepl (CZM method) to deal with zeros based Gregory Gloor's compositional biplot tutorial, and have kept using it with other packages to stay consistent. I downloaded your r scripts from the first phylofactor paper and noticed you cautioned against it because "it can lead to negative-valued compositions." I was hoping you could expand a little more on what this means and why its inappropriate. Thanks for any insight!

**Comment by reptalex** [comment]
If you're happy with your method of zero replacement and have all strictly positive values in your data matrix, you're welcome to plow ahead with the default phylofactorization without worrying about the possibility of negative values. Unfortunately I don't have the bandwidth to discuss compositional data analysis here, but happy to help with any package bugs if you encounter them!

**Comment by biggs-biggsby** [comment]
Okay! So by negative valued compositions you mean any values that are negative. Awesome! Just checked and all of my counts are positive. Thanks for the speedy reply!
