### ISSUE TITLE
Comparing tow microbiomes

### ISSUE THREAD

**Issue by SilasK** [reptalex/phylofactor#31]
Hey @reptalex, 

I have again a special application for phylofactor. 
My goal is to compare two microbiomes from two different host organisms. I have count data for both microbiomes.

The problem, there are almost no shared species, only at the genus level, the two microbiomes are comparable. 

I assume it is difficult to work with missing data in philofactor and filling in 0 for all the missing species, will be kind of a bias.

Do you have an idea how to summarize the counts on genus level?

**Comment by reptalex** [comment]
Lots of options for you!

First, there’s the `gpf` function that allows formal count analyses. Second, that function has an input argument min.group.size you can set to 2 if you want to exclude tips. You can do this with a taxonomy tree and it’ll omit species but allow genus, family, class, etc. More generally, you can input your own objective function which will give you access to the resulting data.table indicating species in R|S groups, from which you can set up any rule (e.g. if non-zero less than 5 times, return 0 as objective).

You can also collapse your tree accordingly - for all species in the same genus, sum counts and collapse their mode on the phylogeny (requires congruence btwn phylogeny and genera). Lots of options!
