### ISSUE TITLE
pf.sumary doesn't work on twoSampleFactor

### ISSUE THREAD

**Issue by SilasK** [reptalex/phylofactor#32]
I used twoSampleFactor to construct a partition and would like to see the summary per factor.

Is there a reason why this doesn't work. 

````
> pf.summary(pf,taxonomy ,1)
Error in `[.data.frame`(taxG, , 2) : undefined columns selected

```

**Comment by reptalex** [comment]
Does `summary(pf)` with appropriate input taxonomy, factor etc.? `pf.summary` may be deprecated as it’s what I used before learning about S3 tricks

**Comment by SilasK** [comment]
unfortunately not:
```
> summary(pf,taxonomy,factor=1)
Error in if (PF$phylofactor.fcn == "gpf" & !PF$algorithm == "mStable") { : 
  argument is of length zero
```

thanks for the quick reply.

**Comment by reptalex** [comment]
Thanks for finding that! I'll see if I can put that together sometime. In the meantime, you can use `pf.taxa` to get taxonomic compositions of particular factors and you can use the output `pf$model.fcn` to compute tests for a desired group (in `summary.phylofactor`, I grepl all species by taxonomic names listed in `pf.taxa` and to get relative imortance of taxonomic groups, for every taxonomic id r_i in r1,...,rn in group R, I re-run `pf$model.fcn` for r_i|S and likewise for every taxonomic id s_j in s1,...,sm I re-run R|s_j).

I'll try to put this together before long. I'm a bit swamped this week, but this is an important function so I'll try to get this up & running soon!

**Comment by reptalex** [comment]
Hi @SilasK!

Thank you for your patience here - it's been a hectic month. I've updated the summary.phylofactor function to fix this bug, and it works on my limited test of twoSampleFactor objects - let me know if you have any other issues!

Best,
Alex
