### ISSUE TITLE
phylofactor will not install using R studio on Mac

### ISSUE THREAD

**Issue by hwfes** [reptalex/phylofactor#33]
Dear reptalex/Alex:

Do you know what tools are necessary to build/install phylofactor on a Mac?

Intallation of phylofactor fails no matter how I try to perform it.  You can see below that the error involves lack of tools necessary to compile the package.  I am running R version 4.0.1 and have installed the latest versions of Xcode and gfortran.  Calling pkgbuild to diagnose the problem just brings up some dumb website (https://www.cnet.com/how-to/install-command-line-developer-tools-in-os-x/).  All other recommended packages are running.

I followed installation issue #18, who has/had a similar difficulty.  You recommendation to go to https://github.com/rstudio/tensorflow/issues/133 led to a dead end resolution.

Please suggest a way around this issue because I do not have access to any other computer, etc. to run phylofactor.

Thank you, Howard

> BiocManager::install('reptalex/phylofactor')
Bioconductor version 3.11 (BiocManager 1.30.10), R 4.0.1 (2020-06-06)
Installing github package(s) 'reptalex/phylofactor'
Downloading GitHub repo reptalex/phylofactor@master
Error: Failed to install 'phylofactor' from GitHub:
  Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.

> devtools::install_github('reptalex/phylofactor')
Downloading GitHub repo reptalex/phylofactor@master
Error: Failed to install 'phylofactor' from GitHub:
  Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.

**Comment by reptalex** [comment]
Did you try - 

```
BiocManager::install(c("Biostrings","ggtree"))
devtools::install_github('reptalex/phylofactor')
```

?

**Comment by hwfes** [comment]
Yes, but I tried it again anyway and still got error message "Could not find tools necessary to compile a package."

I am beginning to think it is some MacOS toolchain difficulty and found the following site;

https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/

However, I do not want to do what is recommended at this site until I am sure about my current deduction -- do not want to mess up my current architecture.

Howard
________________________________

**Comment by reptalex** [comment]
That's understandable, and I'm sorry to hear that. Rcpp is a very common package in R - if I understand correctly, your issue will likely extend well beyond phylofactor. In the same way you'll need a machine that can support R, you'll need a machine that supports Rcpp to run this package (many of the underlying stats & other packages are dramatically sped-up by calling scripts in C++ through Rcpp).

Let me know if this issue can't be addressed by install.packages('Rcpp') and following any warning messages that appear there, including the trail you've found on potential compiler tools that may be useful.

Best,
Alex
