### ISSUE TITLE
Multiple Coefficients?

### ISSUE THREAD

**Issue by biggs-biggsby** [reptalex/phylofactor#38]
Hi @reptalex,

I am using Phylofactor to look at 16s balances associated with viral loads. I am using a phyloseq object to do this, am my code looks something similar to this -

pf <- PhyloFactor(phyloseq@otu_table, phyloseq@phy_tree, phyloseq@sam_data$ViralLoad)

When I look at the model, though, there is a coefficient for each value in the viral load metadata. For one metadata category, shouldn't there only be one coefficient for vial load? That is the case with your tutorial regarding latitude, but I can't seem to replicate that with my own data even if I try to format mine similar to how you had yours in the tutorial. Thanks for any help!

**Comment by biggs-biggsby** [comment]
I may have come up with a solution. I think the problem might have been the data type for my metadata. Using as.numeric() on viralLoad seems to have corrected the issue.

**Comment by reptalex** [comment]
Hi there!

Great to hear from you and that sounds like an exciting project. I think that is exactly right: if your meta-data contain only "ViralLoad" then my first question is whether ViralLoad was numeric or (more likely) a factor. Your second responses suggests it was a factor, in which case converting it to a numeric should fix it.

I can't wait to read about what you find!

Best,
Alex

**Comment by reptalex** [comment]
P.S. You may want to select an input `nfactors` argument, otherwise that may take a while and find a lot of factors that are not significant.

Happy phylofactoring!

**Comment by reptalex** [comment]
P.P.S. Not knowing your full study design, but inferring that you're studying some association between viral load on another (presumably microbial) community ecological datasets, you may have important confounds, such as "age" (well known to affect the microbiome), and through customized objective functions (see ? Phylofactor) phylofactorization can still find which lineages are most significantly associated with ViralLoad when controlling for those confounds (e.g. if this were SARS-CoV-2, we might expect higher viral loads in elderly patients, or perhaps if these are fecal viral loads higher viral loads in pediatric patients, and we may want to know how viral load impacts the microbiome controlling for this clear confound of age).
