### ISSUE TITLE
conda recipe for phylofactor

### ISSUE THREAD

**Issue by mortonjt** [reptalex/phylofactor#9]
It would be awesome if there could be a conda recipe on bioconda for phylofactor.
https://github.com/bioconda/bioconda-recipes

It'll make installation super easy.

**Comment by reptalex** [comment]
I'm not sure how to do that - any pointers?

**Comment by mortonjt** [comment]
We'd need to setup a [conda build](https://conda.io/docs/building/recipe.html)
It'll boil down to creating a `build.sh` and a `meta.yaml` file.   We've put together an entire repository of recipes [here](https://github.com/biocore/conda-recipes).  

It just makes it really easy to install packages with a single command.  Personally, I find this the easiest way to install R packages if they have a conda build.  Of course, I'll be happy to help get this started.

**Comment by johnchase** [comment]
@mortonjt Have you installed PhyloFactor on OSX through Conda? I realize there is probably not a recipe out there, but I'm wondering if you have any insight to getting this installed on OSX, I have so far been unsuccessful, though it may very well be an issue unique to my environments

I should also mention that the issue I am running into is with the R package `maps` and nothing to do with PhyloFactor itself

**Comment by reptalex** [comment]
@johnchase correct me if I'm wrong, but I believe the current package (thanks to removing a few dependencies) can be installed on OSX through Conda, no?

**Comment by johnchase** [comment]
@reptalex phylofactor is able to be installed within a conda environment and work with other packages that have been installed in that environment, however I don't believe that there is a conda recipe for phylofactor out there. This would be installing phylofactor with conda along the lines of:

```bash
conda install -c bioconda phylofactor
```

**Comment by reptalex** [comment]
Gotcha - thanks @johnchase for the heads up and clarification! I won't have the bandwidth to do that solo in the near future, but I'm all ears in case there's an easy way to do that.
